#! /bin/bash
##简单if判断
if [ $# -eq 0 ];then
   echo "Input redhat | fedora" >&2
elif [ $1 == redhat ];then
   echo fedora
elif [ $1 == fedora ];then
   echo redhat
else
   echo "Input redhat | fedora" >&2
fi
